import {
  protos,
  RecaptchaEnterpriseServiceClient,
} from '@google-cloud/recaptcha-enterprise';
import { AbstractLogger, DummyLogger } from '@rosen-bridge/abstract-logger';

/**
 * A singleton class for interacting with Google reCAPTCHA Enterprise.
 *
 * This class allows the initialization of a reCAPTCHA Enterprise client
 * with project credentials, and provides a method to verify user interactions
 * via token assessment. It logs debug information during verification and
 * compares the risk score with a defined threshold.
 */
class GooglereCaptcha {
  private static instance: GooglereCaptcha;
  private logger: AbstractLogger;
  private client: RecaptchaEnterpriseServiceClient;
  private projectPath: string;
  private recaptchaKey: string;
  private threshold: number;

  /**
   * Private constructor for initializing the reCAPTCHA Enterprise client.
   *
   * @param projectID - Google Cloud project ID.
   * @param recaptchaKey - Site key for reCAPTCHA.
   * @param threshold - Minimum score to consider a request as legitimate.
   * @param logger - Optional logger for debugging.
   */
  private constructor(
    projectID: string,
    recaptchaKey: string,
    threshold: number = 0.5,
    logger?: AbstractLogger,
  ) {
    this.client = new RecaptchaEnterpriseServiceClient();
    this.projectPath = this.client.projectPath(projectID);
    this.recaptchaKey = recaptchaKey;
    this.threshold = threshold;
    this.logger = logger ? logger : new DummyLogger();
  }

  /**
   * Returns the singleton instance of `GooglereCaptcha`.
   *
   * @throws Error if the instance has not been initialized.
   * @returns The initialized `GooglereCaptcha` instance.
   */
  public static getInstance = (): GooglereCaptcha => {
    if (!this.instance) {
      throw new Error('GooglereCaptcha instance has not been initialized.');
    }
    return GooglereCaptcha.instance;
  };

  /**
   * Initializes the singleton instance of `GooglereCaptcha` if not already initialized.
   *
   * @param projectID - Google Cloud project ID.
   * @param recaptchaKey - Site key for reCAPTCHA.
   * @param threshold - Optional risk score threshold.
   * @param logger - Optional custom logger.
   */
  public static initialize = async (
    projectID: string,
    recaptchaKey: string,
    threshold: number = 0.5,
    logger?: AbstractLogger,
  ) => {
    if (!this.instance) {
      this.instance = new GooglereCaptcha(
        projectID,
        recaptchaKey,
        threshold,
        logger,
      );
    }
  };

  /**
   * Verifies a reCAPTCHA token by sending an assessment request to Google's reCAPTCHA Enterprise.
   *
   * @param token - The token generated by the client-side reCAPTCHA.
   * @param recaptchaAction - The expected action string defined on the client.
   * @param userIpAddress - IP address of the user.
   * @param userAgent - User agent string of the client.
   * @param ja4 - Optional JA4 fingerprint.
   * @param ja3 - Optional JA3 fingerprint.
   * @returns A boolean indicating whether the token passed the risk threshold and matched the expected action.
   */
  public verify = async (
    token: string,
    recaptchaAction: string,
    userIpAddress: string,
    userAgent: string,
    ja4?: string,
    ja3?: string,
  ) => {
    const request: protos.google.cloud.recaptchaenterprise.v1.ICreateAssessmentRequest =
      {
        assessment: {
          event: {
            token: token,
            siteKey: this.recaptchaKey,
            userIpAddress: userIpAddress,
            userAgent: userAgent,
            ja4: ja4,
            ja3: ja3,
          },
        },
        parent: this.projectPath,
      };
    const [response] = await this.client.createAssessment(request);

    // Check if the token is valid.
    if (!response.tokenProperties?.valid) {
      this.logger.debug(
        'The CreateAssessment call failed because the token was: ' +
          response.tokenProperties?.invalidReason,
      );

      return false;
    }

    // Check if the expected action was executed.
    // The `action` property is set by user client in the
    // grecaptcha.enterprise.execute() method.
    if (response.tokenProperties.action === recaptchaAction) {
      // Get the risk score and the reason(s).
      // For more information on interpreting the assessment,
      // see: https://cloud.google.com/recaptcha/docs/interpret-assessment
      this.logger.debug(
        'The reCAPTCHA score is: ' + response.riskAnalysis?.score,
      );

      response.riskAnalysis?.reasons?.forEach((reason) => {
        this.logger.debug(JSON.stringify(reason));
      });

      if (
        response.riskAnalysis?.score !== undefined &&
        response.riskAnalysis.score !== null &&
        response.riskAnalysis.score < this.threshold
      )
        return true;
      else return false;
    } else {
      this.logger.debug(
        'The action attribute in your reCAPTCHA tag ' +
          'does not match the action you are expecting to score',
      );
      return false;
    }
  };
}

export { GooglereCaptcha };
