export { setupRecaptcha } from './googleRecaptcha';
export { setupDatabase } from './database';
export { setupFastifyServer, startServerService } from './fastify';
export { setupErgoAuth } from './ergoAuth';
export { setupDiscordAuth } from './discordAuth';
export { setupXAuth } from './xAuth';
export { setupController } from './controller';
export { setupGoogleAuth } from './googleAuth';
export { setupAccountant } from './accountant';
export { setupErgoUtils } from './ergoUtils';
