recaptcha:
  key: '' # 'your-recaptcha-secret-key'

server:
  jwtSecret: '' # 'your-jwt-secret'
  cookie:
    secret: '' # 'your-cookie-secret'

database:
  password: '' # 'faucet_password'

redis:
  password: '' # 'your-redis-password'

discord:
  clientSercret: '' # 'your-discord-client-secret'

x-platform:
  clientSecret: '' # 'your-x-client-secret'
