# logging configuration
logs:
  - type: 'file'
    path: './logs/'
    maxSize: '20m'
    maxFiles: '14d'
    level: 'info'
  - type: 'console'
    level: 'info'

recaptcha:
  activate: true
  key: ''
  threshold: 0.5
  hostnames:
    - 'localhost'

server:
  port: 3000
  host: 0.0.0.0
  corsOrigins: []
  jwtSecret: ''
  jwtExpiration: 86400
  activeFastifyLogger: false
  swaggerUi:
    routePrefix: '/docs'
    uiConfig:
      docExpansion: true
      deepLinking: false
  cookie:
    secret: ''
    signed: false
    name: 'refreshToken'
    httpOnly: true
    secure: false
    sameSite: 'lax'
    path: '/'
    domain: ''
    maxAge: 7200

database:
  type: 'postgres'
  database: ''
  host: 'postgres'
  port: 5432
  username: ''
  password: ''
  logging: false

redis:
  host: 'redis'
  port: 6379
  password: ''

ergoAuth:
  challengeExpirySeconds: 300
  refreshTokenExpirySeconds: 2592000
  accessTokenExpirySeconds: 3600
  networkAddress: 'mainnet'

discord:
  clientID: ''
  clientSecret: ''
  redirectURL: ''
  scope: 'identify email'
  expiresTime: 7200
  sessionTTL: 3600

x-platform:
  clientID: ''
  clientSecret: ''
  redirectURL: ''
  scope: 'tweet.read users.read offline.access'
  expiresTime: 7200
  sessionTTL: 3600

googleAuth:
  clientID: ''
  clientSecret: ''
  redirectURL: ''
  scope: 'email profile openid'
  expiresTime: 7200
  sessionTTL: 3600

ergo:
  network: 'mainnet'
  nodeURL: ''
  minNanoErg: 10000000
  minFee: 1000000

URLs:
  frontCallbackURL: ''
