name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [dev]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Check
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Type Check
        run: npm run type-check

      - name: Depcheck per package
        run: |
          IGNORE_PACKAGES="@changesets/cli,@rosen-bridge/changeset-formatter,@typescript-eslint/eslint-plugin,@typescript-eslint/parser,eslint,eslint-config-prettier,vitest,@vitest/coverage-istanbul,husky,lint-staged,@types/node,prettier,pg,typescript,tsx"
          IGNORE_PATHS="node_modules,dist,coverage,*.tsbuildinfo,.vite,.turbo"


          for dir in $(find packages services -name package.json -exec dirname {} \;); do
            npx depcheck --ignores="$IGNORE_PACKAGES" --ignore-patterns="$IGNORE_PATHS" --quiet $dir
          done

      - name: Run Tests
        run: npm run test

  changeset-check:
    name: Changeset Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Check for Changeset
        run: |
          # Use the official changeset CLI to check for required changesets
          # This will exit with error if there are no changesets for changes since the base branch
          npx @changesets/cli status --since=origin/${{ github.base_ref }}
